apiVersion: 1
datasources:
  - name: ShopMetrics PostgreSQL
    type: postgres
    uid: shopmetrics-postgres
    url: postgres:5432
    database: shopmetrics
    user: grafana_user
    secureJsonData:
      password: grafana_pass
    jsonData:
      sslMode: disable
    editable: true

  - name: Infinity
    type: yesoreyeram-infinity-datasource
    uid: shopmetrics-infinity
    # editable: true
